build: 
  script: 
    - "echo \"Building\""
    - "echo \"Setting up drone kit\""
  stage: build
stages: "-build -test"
test: 
  script: 
    - "echo \"Testing...\""
    - "echo \"Starting all unit tests!\""
  stage: test