build-job:
  stage: build
  script:
    - echo "building..."
    - echo "setting up drone-kit"

pylint:
  stage: Analysis
  allow_failure: true
  script:
   - pylint *.py **/*.py
test:
  stage: test
  script:
    - echo "starting unit tests!"
    - python -m unittest test/communications/*
   

