build-job:
  stage: build
  script:
    - echo "building..."
    - echo "setting up drone-kit"

test:
  stage: test
  script:
    - echo "starting unit tests!"
    - python -m unittest discover -s <test> -p '*_test.py'

