stages:
  - Analysis
  - Build
  - Test

before_script:
  - python --version
  - pip install pylint


build-job:
  stage: Build
  script:
    - echo "building..."
    - echo "setting up drone-kit"

pylint:
  stage: Analysis
  allow_failure: true
  script:
   - pylint communications.py
test:
  stage: Test
  script:
    - echo "starting unit tests!"
    - python -m unittest test/communications/*
   

