build-job:
  stage: build
  script:
    - echo "building..."
    - echo "setting up drone-kit"

test:
  stage: test
  script:
    - echo "starting unit tests!"
    - python -m unittest test/flight/navigation/translation/flight_status_tests.py
   

